version: '3'
services:
  app:
    container_name: survey_app_test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
        - api_test:/app/src/app/
    depends_on:
      - mysql_test
    networks:
      - fullstack


  mysql_test:
    image: mysql:8.0
    container_name: full_db_test_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${TestDbHost}
      - MYSQL_USER=${TestDbUser}
      - MYSQL_PASSWORD=${TestDbPassword}
      - MYSQL_DATABASE=${TestDbName}
      - MYSQL_ROOT_PASSWORD=${TestDbPort}
    volumes:
      - database_mysql_test:/var/lib/mysql
    networks:
      - fullstack


volumes:
  api_test:
  database_mysql_test:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge